openapi: 3.1.0
info:
  title: x0 HTTP API
  version: 2.0.0

paths:
  /info:
    $ref: "paths/info.yml"
  /namespaces:
    $ref: "paths/namespaces.yml"
  /namespaces/{namespace_id}:
    $ref: "paths/namespaces-:namespace_id.yml"
  /namespaces/{namespace_id}/reset_token:
    $ref: "paths/namespaces-:namespace_id-reset_token.yml"
